# Generated by Django 6.0.3 on 2026-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='files',
            field=models.FileField(default='misc/default.txt', upload_to='misc/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
